name: antidrugs
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  dio: ^5.0.0
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1
  go_router: ^7.0.1
  equatable: ^2.0.5
  flutter_bloc: ^8.1.2
  get_it: ^7.6.0
  flutter_svg: ^2.0.2
  loading_overlay: ^0.3.0
  shared_preferences: ^2.0.18
  another_flushbar: ^1.12.30
  url_launcher: ^6.1.10
  geolocator: ^9.0.2
  cached_network_image: ^3.2.3
  flutter_multi_formatter: ^2.11.9
  webview_flutter: ^4.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner:

flutter_gen:
  output: lib/gen/

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml


flutter:
  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
        - asset: assets/fonts/OpenSans-Light.ttf
          style: italic
        - asset: assets/fonts/OpenSans-Light.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/OpenSans-Medium.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/OpenSans-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700
        - asset: assets/fonts/OpenSans-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/OpenSans-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/OpenSans-ExtraBoldItalic.ttf
          weight: 800
          style: italic
